// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication18.Data;

#nullable disable

namespace WebApplication18.Migrations
{
    [DbContext(typeof(resturantsContext))]
    partial class resturantsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApplication18.Models.categorie", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("resturantsid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("resturantsid");

                    b.ToTable("categorie");
                });

            modelBuilder.Entity("WebApplication18.Models.itemoptions", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int>("menu_itemid")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("menu_itemid");

                    b.ToTable("itemoptions");
                });

            modelBuilder.Entity("WebApplication18.Models.menu_item", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int>("categorieid")
                        .HasColumnType("int");

                    b.Property<string>("item_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("categorieid");

                    b.ToTable("menu_item");
                });

            modelBuilder.Entity("WebApplication18.Models.option", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isSelected")
                        .HasColumnType("bit");

                    b.Property<int>("itemoptionsid")
                        .HasColumnType("int");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("itemoptionsid");

                    b.ToTable("option");
                });

            modelBuilder.Entity("WebApplication18.Models.resturants", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("resturants");
                });

            modelBuilder.Entity("WebApplication18.Models.categorie", b =>
                {
                    b.HasOne("WebApplication18.Models.resturants", null)
                        .WithMany("categorie")
                        .HasForeignKey("resturantsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApplication18.Models.itemoptions", b =>
                {
                    b.HasOne("WebApplication18.Models.menu_item", null)
                        .WithMany("itemoptions")
                        .HasForeignKey("menu_itemid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApplication18.Models.menu_item", b =>
                {
                    b.HasOne("WebApplication18.Models.categorie", null)
                        .WithMany("items")
                        .HasForeignKey("categorieid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApplication18.Models.option", b =>
                {
                    b.HasOne("WebApplication18.Models.itemoptions", null)
                        .WithMany("options")
                        .HasForeignKey("itemoptionsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApplication18.Models.categorie", b =>
                {
                    b.Navigation("items");
                });

            modelBuilder.Entity("WebApplication18.Models.itemoptions", b =>
                {
                    b.Navigation("options");
                });

            modelBuilder.Entity("WebApplication18.Models.menu_item", b =>
                {
                    b.Navigation("itemoptions");
                });

            modelBuilder.Entity("WebApplication18.Models.resturants", b =>
                {
                    b.Navigation("categorie");
                });
#pragma warning restore 612, 618
        }
    }
}
